server:
  port: 8091
  servlet:
    context-path: /bookmy/api/v1

#H2
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:bookmy
    driverClassName: org.h2.Driver
    username: sa
    password: test
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: false
        format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"